[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.7.2", features = ["web-axum"] }
axum = "0.5.17"
sync_wrapper = "0.1.1"